[alembic]
script_location = apps/api/app/db/alembic
sqlalchemy.url = postgresql+psycopg://reachy_dev@/reachy_local?host=/var/run/postgresql

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = WARN
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s %(message)s